name: Preview Master
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [v16.18.1]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            ## TODO:下方修改一处
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST_NANJING2 }}
                username: ${{ secrets.DEPLOY_USER }}
                key: ${{ secrets.DEPLOY_KEY }}
                script: |
                    cd /www/wwwroot/jx3box/jx3box-v2
                    cd index
                    git checkout gh-pages
                    git pull origin gh-pages
